name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            OTTERAI_USERNAME: ${{ secrets.OTTERAI_USERNAME }}
            OTTERAI_PASSWORD: ${{ secrets.OTTERAI_PASSWORD }}
            TEST_OTTERAI_SPEECH_OTID: ${{ secrets.TEST_OTTERAI_SPEECH_OTID }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: make init-dev

            - name: Run non-integration tests
              run: make test-no-integration

            - name: Run integration tests
              if: ${{ env.OTTERAI_USERNAME != '' && env.OTTERAI_PASSWORD != '' }}
              run: make test-integration
